[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
prediction_market = "wV5jwseh9fQfrdHUbxafCfGpvuWbQaNYqQaBJS8vuVa"

[programs.devnet]
prediction_market = "wV5jwseh9fQfrdHUbxafCfGpvuWbQaNYqQaBJS8vuVa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet  = "~/.config/solana/id.json" 

# [scripts]
# test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
